# discord link that gets sent on /discord
discord: https://discord.gg/packetpool/
rules:
  Cheating: Any use of external tools is not allowed.
  Exploiting: Exploiting unintended features of this server is not allowed.
  Chat: Toxicity, spamming, discrimination and other kinds of chat abuse is not allowed.