discord: https://discord.gg/packetpool/
tab:
  header: ""
  footer: "&enetworklayer.net"
rules:
  - "&c1. External tools that give you an advantage are not allowed."
  - "&c2. Exploiting unintended features of this server is not allowed."
  - "&c3. Advertising, spamming, discrimination or any other kind of chat abuse is not allowed."