name: Utilities
version: '${project.version}'
main: me.crackma.utilities.UtilitiesPlugin
author: crackma
website: https://github.com/crackma/
api-version: '1.20'
commands:
  discord:
    description: Sends the discord link.
    permission: utilities.discord
    permission-message: §cYou cannot do that.
    usage: §c/discord
  message:
    description: Send private messages to players.
    aliases: [msg, whisper, w, reply, r]
    permission: utilities.message
    permission-message: §cYou cannot do that.
    usage: §c/message <player> <message>
  mutechat:
    description: Disable chat for most of the players.
    permission: utilities.mutechat
    permission-message: §cYou cannot do that.
    usage: §c/mutechat
  rename:
    description: Rename currently held item.
    permission: utilities.rename
    permission-message: §cYou cannot do that.
    usage: §c/rename <name>
  rules:
    description: View the rules.
    usage: §c/rules
    permission: utilities.rules
    permission-message: §cYou cannot do that.
  spawn:
    description: Teleport to the world spawn.
    permission: utilities.spawn
    permission-message: §cYou cannot do that.
    usage: §c/spawn [player]
  test:
    description: testesstestsetsetestsetsetseesttestesstetestsetsetsetsetsetestestestestetsetsetsestetsetsetsetsestetsetsetesstetesstetesesttesetstestsetetse
  vanish:
    description: Hide from other players.
    permission: utilities.staff
    permission-message: §cYou cannot do that.
    usage: §c/vanish
  ban:
    description: Ban rule breakers.
    permission: utilities.ban
    permission-message: §cYou cannot do that.
    usage: §c/<command> <player> <time> <reason>
  unban:
    description: Revoke bans.
    permission: utilities.ban
    permission-message: §cYou cannot do that.
    usage: §c/<command> <player>
  mute:
    description: Mute rule breakers.
    permission: utilities.mute
    permission-message: §cYou cannot do that.
    usage: §c/<command> <player> <time> <reason>
  unmute:
    description: Revoke mutes.
    permission: utilities.mute
    permission-message: §cYou cannot do that.
    usage: §c/<command> <player>
  rank:
    description: Manage permissions.
    usage: §c/rank help
    permission: utilities.rank
    permission-message: §cYou cannot do that.
  info:
    description: Gives information about a player.
    permission: utilities.info
    permission-message: §cYou cannot do that.
    usage: §c/info <player>